### ISSUE TITLE
[Desktop][Mobile] Сделать так, чтобы название организации было ссылкой на соц. сеть или сайт, указанный организацией при регистрации.

### ISSUE THREAD

**Issue by Omeljusik** [teenjob-by/teenjob_development#184]
### На общей странице
![image](https://user-images.githubusercontent.com/32821205/67313489-b6b0db80-f50b-11e9-90a8-c2b9034cb787.png)

### На странице с объявлением
![image](https://user-images.githubusercontent.com/32821205/67313599-e364f300-f50b-11e9-85ea-9edabc598b65.png)

**Comment by fr0zen** [comment]
Есть вариант - проверять ссылку на валидность

**Comment by Omeljusik** [comment]
Работает с внешней страницы, где список объявлений.


## НО
1. Не работает на внутренних страничках с текстом объявления (проверила в стажировках и мероприятиях)
2. И сайт ломается, при попытке перейти вовнутрь волонтерского объявления. Попробуй нажать на любое http://dev.teenjob.by/offers?volunteering=on

**Comment by Omeljusik** [comment]
Есть.
