### ISSUE TITLE
[Mobile] Убрать кнопки волонтерство, стажировки, мероприятия с главной

### ISSUE THREAD

**Issue by Omeljusik** [teenjob-by/teenjob_development#185]
### Макет https://www.figma.com/file/OD9PcqDHdfLJHDLJi34l3wAH/teenjob?node-id=1817%3A17

Преобразовать кнопки в подзаголовки.

**Comment by fr0zen** [comment]
@Omeljusik актуально?

**Comment by Omeljusik** [comment]
@fr0zen неа, дубль
