### ISSUE TITLE
[SocialNetworks] Добавить кратинки к ссылкам, которые отображаются в вк, фб

### ISSUE THREAD

**Issue by Omeljusik** [teenjob-by/teenjob_development#189]
## Фб
Главная, волонтерство, стажировки, мероприятия и другие -   https://github.com/Omeljusik/teenjob_development/blob/pictures/main_fb.png
Вход и регистрация - https://github.com/Omeljusik/teenjob_development/blob/pictures/entrance.png
Поддержать - https://github.com/Omeljusik/teenjob_development/blob/pictures/support.png

## Вк
Главная и другие - https://github.com/Omeljusik/teenjob_development/blob/pictures/main_vk.png
Вход и регистрация - https://github.com/Omeljusik/teenjob_development/blob/pictures/entrance.png
Поддержать - https://github.com/Omeljusik/teenjob_development/blob/pictures/support.png

vk https://vk.com/teenjob_by
instagram https://www.instagram.com/teenjob.by/?hl=ru
telegram https://t.me/teenjob_by
fb https://www.facebook.com/teenjob.by/

**Comment by Omeljusik** [comment]
Да, работает верно!

**Comment by Omeljusik** [comment]
@fr0zen Не, не работает.
фб
![image](https://user-images.githubusercontent.com/32821205/68018457-409a3a80-fcaa-11e9-8261-95ece47eec66.png)
![image](https://user-images.githubusercontent.com/32821205/68018615-9d95f080-fcaa-11e9-8a5a-2901851b5ceb.png)

Вк
![image](https://user-images.githubusercontent.com/32821205/68018476-4b54cf80-fcaa-11e9-9cfd-2012a802e4c7.png)
![image](https://user-images.githubusercontent.com/32821205/68018529-66274400-fcaa-11e9-9ae6-adfe6e8b762a.png)
![image](https://user-images.githubusercontent.com/32821205/68018556-793a1400-fcaa-11e9-8c1d-9e51bdc9ea81.png)
![image](https://user-images.githubusercontent.com/32821205/68018580-8820c680-fcaa-11e9-9f55-93e4b4bb6968.png)

**Comment by Omeljusik** [comment]
@fr0zen в основном хорошо. 
### Не хватает картинки для страниц:
https://teenjob.by/register 
![image](https://user-images.githubusercontent.com/32821205/68126467-f1137300-ff24-11e9-9d6d-d2b5d6ec9437.png)

### Для этих та же картинка, что и для главной:
https://teenjob.by/terms-of-use
https://teenjob.by/conditions
https://teenjob.by/contacts

**Comment by fr0zen** [comment]
@Omeljusik пока на деве

**Comment by Omeljusik** [comment]
Да, работает!
