### ISSUE TITLE
Мероприятия по окончании переходят, а затем удаляются из прошедших

### ISSUE THREAD

**Issue by Omeljusik** [teenjob-by/teenjob_development#202]
5.11.2019
По-моему как только появляется 2 прошедших мероприятия, они исчезают из вывода в Прошедшие, но не факт - четкой закономерности не скажу. Но точно видела в прошедших 1 мероприятие. Должно быть хотябы 2-3, учитывая, что 2-3 я архивировала или удаляла, поэтому они не будут отображены в прошедших.
![image](https://user-images.githubusercontent.com/32821205/68202154-36db4480-ffd4-11e9-9dfb-329b8a269aae.png)

**Comment by fr0zen** [comment]
@Omeljusik актуально?

**Comment by Omeljusik** [comment]
Готово)

**Comment by Omeljusik** [comment]
работает
