### ISSUE TITLE
[Partners] Добавить лого партнера

### ISSUE THREAD

**Issue by Omeljusik** [teenjob-by/teenjob_development#229]
Ссылка на макеты: https://www.figma.com/file/OD9PcqDHdfLJHDLJi34l3wAH/teenjob?node-id=1983%3A22

Ссылка при нажатии на картинку (открывается в новой вкладке): https://www.facebook.com/TerytoryjaPravou/

На мобике "карусель" - листается стрелками https://www.figma.com/file/OD9PcqDHdfLJHDLJi34l3wAH/teenjob?node-id=1983%3A959

**Comment by fr0zen** [comment]
@Omeljusik на продакшене
