### ISSUE TITLE
[Desktop] [Mobile] Убрать пока кнопку с хедера на главной.

### ISSUE THREAD

**Issue by Omeljusik** [teenjob-by/teenjob_development#230]
Привет!
Давай уберем эту кнопку пока что совсем.
![image](https://user-images.githubusercontent.com/32821205/71818271-8b18a880-3099-11ea-9bd5-bd9b26cbeb2f.png)

Или сделать кнопку Добавить объявление на случай, если прейдут именно орагнизации...ее будет проще заметить и захочется нажать...
Кнопка в той же вкладке открывает ссылку https://teenjob.by/login
![image](https://user-images.githubusercontent.com/32821205/71818696-b6e85e00-309a-11ea-89d7-f461a74283cb.png)

**Comment by fr0zen** [comment]
Также заменил текст в меню на "добавить объявление"
