### ISSUE TITLE
Реализовать перевод на белорусский язык.

### ISSUE THREAD

**Issue by fr0zen** [teenjob-by/teenjob_development#236]
- [x] Главная страница +
- [x] Страница логина
- [x] Страница регистрации
- [x] Страница подтверждения
- [x] Личный кабинет +
- [x] Правила пользования сайтом +
- [x] Кто такой волонтер +
- [x] Кто такой стажер +
- [x] Поддержать проект +
- [x] Стажировки
- [x] Мероприятия
- [x] Волонтерство
- [x] Стажировки - внутренняя
- [x] Мероприятия - внутренняя
- [x] Волонтерство - внутренняя
- [x] Отказ от ответственности +
- [x] Какой язык по умолчанию выходит
- [x] Динамические данные (в фильтре)
- [x] Админка сайта - таблицы организаций
- [x] Админка сайта - страница мероприятий
- [x] Админка сайта  - страница стажировок
- [x] Админка сайта - страница волонтерств
- [ ] Админка сайта - Внутренние

**Comment by fr0zen** [comment]
- [ ] Какой язык по умолчанию у вас

**Comment by Omeljusik** [comment]
@fr0zen давай русский сделаем

**Comment by Omeljusik** [comment]
@fr0zen я не отвечаю сразу, потому что не отслеживаю уведомления отсюда. Можешь мне отписываться в телеграм, чтобы я зашла, когда ты прокомментил или сделал что-то, что надо посмотреть? Можешь писать, что-то вроде "посмотри, пожалуйста, сегодня-завтра" или в ближайшие пару часов, или посмотри до среды. 

Включать уведомления мне будет неудобно, потому что отсюда они вроде как редко, а будет сыпоться с почты еще куча всякого Г. 

Как тебе?

**Comment by Omeljusik** [comment]
https://trello.com/c/SioJ5Tx2/94-%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%B5%D1%81%D1%82%D0%B8-%D1%81%D0%B0%D0%B9%D1%82

**Comment by Omeljusik** [comment]
@fr0zen в Падтрымаць, добавь, пожалуйста:

**Comment by Omeljusik** [comment]
@fr0zen Давай лучше в белорусской версии напишем: Падтрымліваюць
![image](https://user-images.githubusercontent.com/32821205/73119340-6d8c7f80-3f71-11ea-96ef-1acc5946a0aa.png)

**Comment by Omeljusik** [comment]
Макеты, как должно быть: https://www.figma.com/file/OD9PcqDHdfLJHDLJi34l3wAH/teenjob?node-id=1909%3A172
![image](https://user-images.githubusercontent.com/32821205/73119363-d4119d80-3f71-11ea-8ee9-7290fdd0e66b.png)

**Comment by Omeljusik** [comment]
![image](https://user-images.githubusercontent.com/32821205/73351917-0d634980-42a1-11ea-98f7-a51e13fb5051.png)
http://dev.teenjob.by/organisation
Нужно: Дадатковы тэл.

**Comment by Omeljusik** [comment]
@fr0zen ## Важно!
При нажатии на Править персоналбную информации в режиме на люьом из языков - сайт ломается. 

http://dev.teenjob.by/organisation - и нажать http://dev.teenjob.by/organisation/edit

**Comment by Omeljusik** [comment]
http://dev.teenjob.by/organisation

![image](https://user-images.githubusercontent.com/32821205/73352454-30422d80-42a2-11ea-9d6a-63e19ae6de7f.png)

![image](https://user-images.githubusercontent.com/32821205/73352512-51a31980-42a2-11ea-8ea4-6d79f75ef31b.png)

![image](https://user-images.githubusercontent.com/32821205/73352564-70091500-42a2-11ea-9514-a88d59f2be2e.png)

![image](https://user-images.githubusercontent.com/32821205/73352711-c1b19f80-42a2-11ea-9001-2d66c04b6d71.png)

**Comment by Omeljusik** [comment]
Заменить "Уласны кабінет" на "Асабісты кабінет" на странице http://dev.teenjob.by/organisation
и "Данные об организации" на "Личный кабинет" и "Асабісты кабінет"
![image](https://user-images.githubusercontent.com/32821205/73379907-2c2f0380-42d4-11ea-9508-3337c3ea6ba5.png)

В меню тоже Асабісты кабінет
на месте этого для организаций
![image](https://user-images.githubusercontent.com/32821205/73380131-892ab980-42d4-11ea-8e99-4dbc0671e9ca.png)

**Comment by Omeljusik** [comment]
Убрать заголовки для каждой вкладки в https://teenjob.by/organisation
И заменить названия на кнопках соответсвенно:
Опубликовать стажировку - Апублікаваць стажыроўку
Опубликовать волонтерство - Апублікаваць валанцёрства
Опубликовать мероприятие - Апублікаваць падзею

**Comment by Omeljusik** [comment]
Повторите пароль
![image](https://user-images.githubusercontent.com/32821205/73380770-a8761680-42d5-11ea-8359-3ac3abfde4dd.png)
