### ISSUE TITLE
[Admin_Org] Добавить "+" к выбору возраста при создании объявления: 14+, 15+, 16+, 17+. 

### ISSUE THREAD

**Issue by Omeljusik** [teenjob-by/teenjob_development#73]
### Добавить + к выбору возраста: 14+, 15+, 16+, 17+. И так во всех типах объявлений (стажировки, волонтерство, мероприятия)
![image](https://user-images.githubusercontent.com/32821205/64712364-c0363500-d4c3-11e9-9303-b94682994d21.png)

**Comment by fr0zen** [comment]
@Omeljusik актуально? тут есть такая ишшью #101

**Comment by Omeljusik** [comment]
Да, дубль - закрыли
